USED_MODELS = ['EB_UBM', 'UBM-IA', 'N-UBM']
EXTENDED_LOG_FORMAT = False

TRAIN_FOR_METRIC = False
PRINT_EBU_STATS = True

MAX_ITERATIONS = 40
DEBUG = False
PRETTY_LOG = True
MIN_DOCS_PER_QUERY = 10
MAX_DOCS_PER_QUERY = 10
SERP_SIZE = 10
TRANSFORM_LOG = False
QUERY_INDEPENDENT_PAGER = False
DEFAULT_REL = 0.5